[package]
name = "mdbook-katex"
version = "0.5.6"
authors = [
    "Lucas Zanini <zanini.lcs@gmail.com>",
    "Steven Hé (Sīchàng) <stevensichanghe@gmail.com>",
]
edition = "2021"
description = "mdBook preprocessor rendering LaTeX equations to HTML."
license = "MIT"
readme = "README.md"
repository = "https://github.com/lzanini/mdbook-katex"

[dependencies]
clap = { version = "4.3", features = ["cargo"] }
mdbook = { version = "0.4.34", default-features = false }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.7"
rayon = "1.7"

# Remember to modify the tests accordingly if you modify this.
[target.'cfg(any(target_os = "macos", all(unix, target_arch = "x86_64"), all(windows, target_env = "gnu")))'.dependencies]
katex = "0.4.6"

[target.'cfg(not(any(target_os = "macos", all(unix, target_arch = "x86_64"), all(windows, target_env = "gnu"))))'.dependencies]
katex = { version = "0.4.6", default-features = false, features = ["duktape"] }

[profile.release]
lto = true
